#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. /opt/openfoam9/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh
runApplication snappyHexMesh -overwrite

runApplication $(getApplication)

simpleFoam -postProcess -func writeCellCentres
# simpleFoam -postProcess -func sample
simpleFoam -postProcess -func cutPlaneSurface

#------------------------------------------------------------------------------
